### ISSUE TITLE
Feature Request: Some feedback

### ISSUE THREAD

**Issue by batrand** [subframe7536/obsidian-theme-maple#20]
Hey there, I've been using the theme for the day and have been really enjoying it! Especially love the animations and just how smooth things kinda flow together. There's a few small things I noticed that I think can be some nice tweaks which I'm thinking of collating all here instead of flooding you with a bunch of small tickets, but of course it's up to you to decide what to incorporate as the developer; just wanted to give you some feedback as a user!

- In dark mode, with rounded title bars and floating tabs, I think the active colour is too dark. The colour of the inactive one (on the right) I feel looks calmer, while the active one is just too dark.
![image](https://user-images.githubusercontent.com/8514709/223390268-c5e82888-b96a-4c83-9f25-730ce28f4f99.png)
I know some people like that really high contrast, but I think it's not for everyone; I personally prefer a bit less contrast.

- So... I don't know how to describe this. I have a setup of tables built from DataView, and with the theme it looks like this. I don't have the design eye to describe what's wrong here... I guess the table feels too... prominent? Maybe having the borders and header could help, but I'm not a designer.
![image](https://user-images.githubusercontent.com/8514709/223391227-519d6e7a-2786-47ab-8ce4-b2029c0e3ebf.png)

- Overall the feel for dark mode is that the contrast feels too high for me. Having more presets with gentler shades of grey, and the other colours as well like reds, yellow, green etc., would feel more comfortable. I think in light mode these feel right, I guess the dark mode version just hasn't been as tuned?

- The Calendar plugin I think does not make very good use of space; lots of whitespace in the margin and just does not feel very well integrated with the theme. Maybe it can be restyled to be a bit more streamlined, tighter somehow. 
![image](https://user-images.githubusercontent.com/8514709/223395532-a172a3ee-41af-4f47-86da-2c59c3f2f0ca.png)
- Also, the floating status bar can cover the calendar!
![image](https://user-images.githubusercontent.com/8514709/223395672-3a8baedb-f16e-46a2-b930-d4cb13d3ecbb.png)

- Trimming the outline pane for headings that are too long. For example lol:
![image](https://user-images.githubusercontent.com/8514709/223393123-ebbe08eb-fbd8-4b14-bf8e-867ecfdc1776.png)

- Speaking of, the titlebar text is too small to comfortably read. I think it feels a bit jarring, but don't know why... maybe cos it's not consistent with the size of the tab's font?
![image](https://user-images.githubusercontent.com/8514709/223393331-682efd7d-6dfb-4735-b3a4-0636f8298271.png)

- Enabling link underline animation will make the text not match font size. Without underline animation option:
![image](https://user-images.githubusercontent.com/8514709/223392582-daf889ca-a444-421f-b868-1c0d7121db55.png)
With underline animation option:
![image](https://user-images.githubusercontent.com/8514709/223392708-03296f84-d481-463b-a32c-438395ec6c66.png)

- Changing the editor line height to less than 2.1 will shift the text inside buttons up; you can see it happen when you slide this slider lol
![image](https://user-images.githubusercontent.com/8514709/223393982-5bbb884b-4ee6-4a0f-af51-646f052f4eb3.png)

- Having a subtler option for dividers used in the headers and the hr element would be nice; some themes I've seen only include a simple thin line. I think the gradient draws too much attention into itself, and personally I prefer a thin, solid line, maybe with the colour of the heading.

These are some of the things I noticed after using the theme today. I really like it, and hope that these are useful for your continued development of the theme :)

**Comment by subframe7536** [comment]
Thanks a lot ❤️ for taking the time to provide such a detailed issue. Your feedback is very valuable and I'll definitely look into it. I'll need some time to work on these tricky bugs and provide you with prompt feedback.

**Comment by subframe7536** [comment]
hello, I have fixed most of the issues you raised in version 0.4.5, but some bugs hadn't or won't be fixed:

> * So... I don't know how to describe this. I have a setup of tables built from DataView, and with the theme it looks like this. I don't have the design eye to describe what's wrong here... I guess the table feels too... prominent? Maybe having the borders and header could help, but I'm not a designer.

this is a hard work on dataview. I will spare a large amount of time on it when I'm not too busy...

> * Also, the floating status bar can cover the calendar!

in 0.4.5, the height of status bar is decreased. also you can set the `user interface > status bar > status bar animation` option like `show on hover` or `scroll out on hover`

> * Trimming the outline pane for headings that are too long. 

you can enable `user interface > outline panel > enable bullet style` to have this feature

> * Enabling link underline animation will make the text not match font size. Without underline animation option:

to approach this animation, the font size must be fixed.

**Comment by subframe7536** [comment]
![image](https://user-images.githubusercontent.com/78338239/223954676-f490919d-6c1a-4ce2-a6df-f4ec108b7f97.png)
how about this？

**Comment by batrand** [comment]
I think this demonstrates better what I mean.
![image](https://user-images.githubusercontent.com/8514709/223958750-92cc4b14-5514-4f44-97e1-c59d38480919.png)

On the left is how the theme Minimal is styling the calendar: you still see all the information and functionality of the plugin in a much tighter styling. On the right is Maple, taking much more screen space, which I prefer to reserve as much as I can for the outline, so I can navigate longer notes better.

**Comment by subframe7536** [comment]
![image](https://user-images.githubusercontent.com/78338239/223969194-be07c235-a170-4e78-aba6-077ed31608a2.png)
I have tried my best 😂

**Comment by batrand** [comment]
hahaha it looks good! for me the tighter the better lol but of course this is just my opinion! the theme's direction and development is still ultimately your decision
